apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-news
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: news_analytics
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: clickhouse
